-- =============================================================
-- 01_create_staging_tables.sql
-- Raw ingestion layer — matches actual DE-SynPUF carrier claims
-- wide/line-level schema (PRF_PHYSN_NPI_* per line, no AT_PHYSN_NPI).
--
-- DE-SynPUF carrier claims are structured as one row per CLAIM,
-- with up to 13 claim lines embedded as suffixed columns (_1.._13).
-- The performing physician NPI per line is PRF_PHYSN_NPI_1..13.
-- Billing amounts per line: LINE_ALOWD_CHRG_AMT_*, LINE_NCH_PMT_AMT_*
-- =============================================================

CREATE SCHEMA IF NOT EXISTS staging;

-- -------------------------------------------------------------
-- Beneficiary Summary
-- -------------------------------------------------------------
DROP TABLE IF EXISTS staging.beneficiary_summary CASCADE;
CREATE TABLE staging.beneficiary_summary (
    desynpuf_id               VARCHAR(50),
    bene_birth_dt             VARCHAR(10),
    bene_death_dt             VARCHAR(10),
    bene_sex_ident_cd         VARCHAR(5),
    bene_race_cd              VARCHAR(5),
    bene_esrd_ind             VARCHAR(5),
    sp_state_code             VARCHAR(5),
    bene_county_cd            VARCHAR(10),
    bene_hi_cvrage_tot_mons   VARCHAR(5),
    bene_smi_cvrage_tot_mons  VARCHAR(5),
    bene_hmo_cvrage_tot_mons  VARCHAR(5),
    plan_cvrg_mos_num         VARCHAR(5),
    sp_alzhdmta               VARCHAR(5),
    sp_chf                    VARCHAR(5),
    sp_chrnkidn               VARCHAR(5),
    sp_cncr                   VARCHAR(5),
    sp_copd                   VARCHAR(5),
    sp_depressn               VARCHAR(5),
    sp_diabetes               VARCHAR(5),
    sp_ischmcht               VARCHAR(5),
    sp_osteoprs               VARCHAR(5),
    sp_ra_oa                  VARCHAR(5),
    sp_strketia               VARCHAR(5),
    medreimb_ip               VARCHAR(20),
    benres_ip                 VARCHAR(20),
    pppymt_ip                 VARCHAR(20),
    medreimb_op               VARCHAR(20),
    benres_op                 VARCHAR(20),
    pppymt_op                 VARCHAR(20),
    medreimb_car              VARCHAR(20),
    benres_car                VARCHAR(20),
    pppymt_car                VARCHAR(20),
    year                      SMALLINT,
    sample_id                 SMALLINT
);

-- -------------------------------------------------------------
-- Carrier Claims — actual DE-SynPUF wide/line-level schema
-- Each claim has up to 13 lines. PRF_PHYSN_NPI_N = performing
-- physician NPI on line N. LINE_ALOWD_CHRG_AMT_N = allowed
-- charge on line N. LINE_NCH_PMT_AMT_N = Medicare payment on line N.
-- -------------------------------------------------------------
DROP TABLE IF EXISTS staging.carrier_claims CASCADE;
CREATE TABLE staging.carrier_claims (
    desynpuf_id               VARCHAR(50),
    clm_id                    VARCHAR(50),
    clm_from_dt               VARCHAR(10),
    clm_thru_dt               VARCHAR(10),
    -- Diagnosis codes
    icd9_dgns_cd_1            VARCHAR(10),
    icd9_dgns_cd_2            VARCHAR(10),
    icd9_dgns_cd_3            VARCHAR(10),
    icd9_dgns_cd_4            VARCHAR(10),
    icd9_dgns_cd_5            VARCHAR(10),
    icd9_dgns_cd_6            VARCHAR(10),
    icd9_dgns_cd_7            VARCHAR(10),
    icd9_dgns_cd_8            VARCHAR(10),
    -- Performing physician NPIs (one per claim line)
    prf_physn_npi_1           VARCHAR(20),
    prf_physn_npi_2           VARCHAR(20),
    prf_physn_npi_3           VARCHAR(20),
    prf_physn_npi_4           VARCHAR(20),
    prf_physn_npi_5           VARCHAR(20),
    prf_physn_npi_6           VARCHAR(20),
    prf_physn_npi_7           VARCHAR(20),
    prf_physn_npi_8           VARCHAR(20),
    prf_physn_npi_9           VARCHAR(20),
    prf_physn_npi_10          VARCHAR(20),
    prf_physn_npi_11          VARCHAR(20),
    prf_physn_npi_12          VARCHAR(20),
    prf_physn_npi_13          VARCHAR(20),
    -- Tax numbers (provider billing entity, one per line)
    tax_num_1                 VARCHAR(20),
    tax_num_2                 VARCHAR(20),
    tax_num_3                 VARCHAR(20),
    tax_num_4                 VARCHAR(20),
    tax_num_5                 VARCHAR(20),
    tax_num_6                 VARCHAR(20),
    tax_num_7                 VARCHAR(20),
    tax_num_8                 VARCHAR(20),
    tax_num_9                 VARCHAR(20),
    tax_num_10                VARCHAR(20),
    tax_num_11                VARCHAR(20),
    tax_num_12                VARCHAR(20),
    tax_num_13                VARCHAR(20),
    -- HCPCS procedure codes (one per line)
    hcpcs_cd_1                VARCHAR(10),
    hcpcs_cd_2                VARCHAR(10),
    hcpcs_cd_3                VARCHAR(10),
    hcpcs_cd_4                VARCHAR(10),
    hcpcs_cd_5                VARCHAR(10),
    hcpcs_cd_6                VARCHAR(10),
    hcpcs_cd_7                VARCHAR(10),
    hcpcs_cd_8                VARCHAR(10),
    hcpcs_cd_9                VARCHAR(10),
    hcpcs_cd_10               VARCHAR(10),
    hcpcs_cd_11               VARCHAR(10),
    hcpcs_cd_12               VARCHAR(10),
    hcpcs_cd_13               VARCHAR(10),
    -- Medicare payment per line (what CMS actually paid)
    line_nch_pmt_amt_1        VARCHAR(20),
    line_nch_pmt_amt_2        VARCHAR(20),
    line_nch_pmt_amt_3        VARCHAR(20),
    line_nch_pmt_amt_4        VARCHAR(20),
    line_nch_pmt_amt_5        VARCHAR(20),
    line_nch_pmt_amt_6        VARCHAR(20),
    line_nch_pmt_amt_7        VARCHAR(20),
    line_nch_pmt_amt_8        VARCHAR(20),
    line_nch_pmt_amt_9        VARCHAR(20),
    line_nch_pmt_amt_10       VARCHAR(20),
    line_nch_pmt_amt_11       VARCHAR(20),
    line_nch_pmt_amt_12       VARCHAR(20),
    line_nch_pmt_amt_13       VARCHAR(20),
    -- Beneficiary Part B deductible per line
    line_bene_ptb_ddctbl_amt_1  VARCHAR(20),
    line_bene_ptb_ddctbl_amt_2  VARCHAR(20),
    line_bene_ptb_ddctbl_amt_3  VARCHAR(20),
    line_bene_ptb_ddctbl_amt_4  VARCHAR(20),
    line_bene_ptb_ddctbl_amt_5  VARCHAR(20),
    line_bene_ptb_ddctbl_amt_6  VARCHAR(20),
    line_bene_ptb_ddctbl_amt_7  VARCHAR(20),
    line_bene_ptb_ddctbl_amt_8  VARCHAR(20),
    line_bene_ptb_ddctbl_amt_9  VARCHAR(20),
    line_bene_ptb_ddctbl_amt_10 VARCHAR(20),
    line_bene_ptb_ddctbl_amt_11 VARCHAR(20),
    line_bene_ptb_ddctbl_amt_12 VARCHAR(20),
    line_bene_ptb_ddctbl_amt_13 VARCHAR(20),
    -- Primary payer paid per line
    line_bene_prmry_pyr_pd_amt_1  VARCHAR(20),
    line_bene_prmry_pyr_pd_amt_2  VARCHAR(20),
    line_bene_prmry_pyr_pd_amt_3  VARCHAR(20),
    line_bene_prmry_pyr_pd_amt_4  VARCHAR(20),
    line_bene_prmry_pyr_pd_amt_5  VARCHAR(20),
    line_bene_prmry_pyr_pd_amt_6  VARCHAR(20),
    line_bene_prmry_pyr_pd_amt_7  VARCHAR(20),
    line_bene_prmry_pyr_pd_amt_8  VARCHAR(20),
    line_bene_prmry_pyr_pd_amt_9  VARCHAR(20),
    line_bene_prmry_pyr_pd_amt_10 VARCHAR(20),
    line_bene_prmry_pyr_pd_amt_11 VARCHAR(20),
    line_bene_prmry_pyr_pd_amt_12 VARCHAR(20),
    line_bene_prmry_pyr_pd_amt_13 VARCHAR(20),
    -- Coinsurance per line
    line_coinsrnc_amt_1       VARCHAR(20),
    line_coinsrnc_amt_2       VARCHAR(20),
    line_coinsrnc_amt_3       VARCHAR(20),
    line_coinsrnc_amt_4       VARCHAR(20),
    line_coinsrnc_amt_5       VARCHAR(20),
    line_coinsrnc_amt_6       VARCHAR(20),
    line_coinsrnc_amt_7       VARCHAR(20),
    line_coinsrnc_amt_8       VARCHAR(20),
    line_coinsrnc_amt_9       VARCHAR(20),
    line_coinsrnc_amt_10      VARCHAR(20),
    line_coinsrnc_amt_11      VARCHAR(20),
    line_coinsrnc_amt_12      VARCHAR(20),
    line_coinsrnc_amt_13      VARCHAR(20),
    -- Allowed charge per line (key fraud signal — what Medicare approved)
    line_alowd_chrg_amt_1     VARCHAR(20),
    line_alowd_chrg_amt_2     VARCHAR(20),
    line_alowd_chrg_amt_3     VARCHAR(20),
    line_alowd_chrg_amt_4     VARCHAR(20),
    line_alowd_chrg_amt_5     VARCHAR(20),
    line_alowd_chrg_amt_6     VARCHAR(20),
    line_alowd_chrg_amt_7     VARCHAR(20),
    line_alowd_chrg_amt_8     VARCHAR(20),
    line_alowd_chrg_amt_9     VARCHAR(20),
    line_alowd_chrg_amt_10    VARCHAR(20),
    line_alowd_chrg_amt_11    VARCHAR(20),
    line_alowd_chrg_amt_12    VARCHAR(20),
    line_alowd_chrg_amt_13    VARCHAR(20),
    -- Processing indicator per line
    line_prcsg_ind_cd_1       VARCHAR(5),
    line_prcsg_ind_cd_2       VARCHAR(5),
    line_prcsg_ind_cd_3       VARCHAR(5),
    line_prcsg_ind_cd_4       VARCHAR(5),
    line_prcsg_ind_cd_5       VARCHAR(5),
    line_prcsg_ind_cd_6       VARCHAR(5),
    line_prcsg_ind_cd_7       VARCHAR(5),
    line_prcsg_ind_cd_8       VARCHAR(5),
    line_prcsg_ind_cd_9       VARCHAR(5),
    line_prcsg_ind_cd_10      VARCHAR(5),
    line_prcsg_ind_cd_11      VARCHAR(5),
    line_prcsg_ind_cd_12      VARCHAR(5),
    line_prcsg_ind_cd_13      VARCHAR(5),
    -- Line-level diagnosis codes
    line_icd9_dgns_cd_1       VARCHAR(10),
    line_icd9_dgns_cd_2       VARCHAR(10),
    line_icd9_dgns_cd_3       VARCHAR(10),
    line_icd9_dgns_cd_4       VARCHAR(10),
    line_icd9_dgns_cd_5       VARCHAR(10),
    line_icd9_dgns_cd_6       VARCHAR(10),
    line_icd9_dgns_cd_7       VARCHAR(10),
    line_icd9_dgns_cd_8       VARCHAR(10),
    line_icd9_dgns_cd_9       VARCHAR(10),
    line_icd9_dgns_cd_10      VARCHAR(10),
    line_icd9_dgns_cd_11      VARCHAR(10),
    line_icd9_dgns_cd_12      VARCHAR(10),
    line_icd9_dgns_cd_13      VARCHAR(10),
    sample_id                 SMALLINT
);

-- -------------------------------------------------------------
-- Outpatient Claims
-- -------------------------------------------------------------
DROP TABLE IF EXISTS staging.outpatient_claims CASCADE;
CREATE TABLE staging.outpatient_claims (
    desynpuf_id               VARCHAR(50),
    clm_id                    VARCHAR(50),
    clm_from_dt               VARCHAR(10),
    clm_thru_dt               VARCHAR(10),
    prvdr_num                 VARCHAR(20),
    clm_pmt_amt               VARCHAR(20),
    nch_prmry_pyr_clm_pd_amt  VARCHAR(20),
    at_physn_npi              VARCHAR(20),
    op_physn_npi              VARCHAR(20),
    clm_fac_type_cd           VARCHAR(5),
    clm_srvc_clsfctn_type_cd  VARCHAR(5),
    clm_freq_cd               VARCHAR(5),
    icd9_dgns_cd_1            VARCHAR(10),
    icd9_dgns_cd_2            VARCHAR(10),
    icd9_dgns_cd_3            VARCHAR(10),
    icd9_dgns_cd_4            VARCHAR(10),
    icd9_dgns_cd_5            VARCHAR(10),
    icd9_dgns_cd_6            VARCHAR(10),
    icd9_dgns_cd_7            VARCHAR(10),
    icd9_dgns_cd_8            VARCHAR(10),
    icd9_dgns_cd_9            VARCHAR(10),
    icd9_dgns_cd_10           VARCHAR(10),
    hcpcs_cd_1                VARCHAR(10),
    hcpcs_cd_2                VARCHAR(10),
    hcpcs_cd_3                VARCHAR(10),
    hcpcs_cd_4                VARCHAR(10),
    hcpcs_cd_5                VARCHAR(10),
    hcpcs_cd_6                VARCHAR(10),
    hcpcs_cd_7                VARCHAR(10),
    hcpcs_cd_8                VARCHAR(10),
    hcpcs_cd_9                VARCHAR(10),
    hcpcs_cd_10               VARCHAR(10),
    hcpcs_cd_11               VARCHAR(10),
    hcpcs_cd_12               VARCHAR(10),
    hcpcs_cd_13               VARCHAR(10),
    hcpcs_cd_14               VARCHAR(10),
    hcpcs_cd_15               VARCHAR(10),
    hcpcs_cd_16               VARCHAR(10),
    hcpcs_cd_17               VARCHAR(10),
    hcpcs_cd_18               VARCHAR(10),
    hcpcs_cd_19               VARCHAR(10),
    hcpcs_cd_20               VARCHAR(10),
    hcpcs_cd_21               VARCHAR(10),
    hcpcs_cd_22               VARCHAR(10),
    hcpcs_cd_23               VARCHAR(10),
    hcpcs_cd_24               VARCHAR(10),
    hcpcs_cd_25               VARCHAR(10),
    hcpcs_cd_26               VARCHAR(10),
    hcpcs_cd_27               VARCHAR(10),
    hcpcs_cd_28               VARCHAR(10),
    hcpcs_cd_29               VARCHAR(10),
    hcpcs_cd_30               VARCHAR(10),
    hcpcs_cd_31               VARCHAR(10),
    hcpcs_cd_32               VARCHAR(10),
    hcpcs_cd_33               VARCHAR(10),
    hcpcs_cd_34               VARCHAR(10),
    hcpcs_cd_35               VARCHAR(10),
    hcpcs_cd_36               VARCHAR(10),
    hcpcs_cd_37               VARCHAR(10),
    hcpcs_cd_38               VARCHAR(10),
    hcpcs_cd_39               VARCHAR(10),
    hcpcs_cd_40               VARCHAR(10),
    hcpcs_cd_41               VARCHAR(10),
    hcpcs_cd_42               VARCHAR(10),
    hcpcs_cd_43               VARCHAR(10),
    hcpcs_cd_44               VARCHAR(10),
    hcpcs_cd_45               VARCHAR(10),
    revenue_cd_1              VARCHAR(10),
    revenue_cd_2              VARCHAR(10),
    revenue_cd_3              VARCHAR(10),
    revenue_cd_4              VARCHAR(10),
    revenue_cd_5              VARCHAR(10),
    sample_id                 SMALLINT
);

-- Load tracking
DROP TABLE IF EXISTS staging.load_log CASCADE;
CREATE TABLE staging.load_log (
    id          SERIAL PRIMARY KEY,
    table_name  VARCHAR(100),
    sample_id   SMALLINT,
    file_name   VARCHAR(255),
    rows_loaded INTEGER,
    loaded_at   TIMESTAMP DEFAULT NOW(),
    status      VARCHAR(20) DEFAULT 'success'
);

COMMENT ON SCHEMA staging IS
    'Raw ingestion layer. Matches actual DE-SynPUF wide/line-level schema.';